"""add plan

Revision ID: 228680604c22
Revises: 
Create Date: 2017-04-02 18:39:26.053285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228680604c22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
